plugins:
    - {name: static_map,        type: "costmap_2d::StaticLayer"}
    - {name: inflation,         type: "costmap_2d::InflationLayer"}

publish_frequency: 1.0

footprint: [[ 0.35,  0.35],
            [-0.35,  0.35],
            [-0.35, -0.35],
            [ 0.35, -0.35]]

transform_tolerance: 1
global_frame: /map
robot_base_frame: base_link_real
update_frequency: 1
planner_patience: 15

static_map:
    map_topic: map
    track_unknown_space: true

inflation:
    inflation_radius: 0.9

